Repository nrc-cnrc/EGSnrc, pull requests merged in 2018-04, with the labels that each got.

#420 Fix egs++ particle tracks crash on Windows 10
  HEN_HOUSE/egs++/egs_particle_track.cpp
  HEN_HOUSE/egs++/egs_particle_track.h
Labels: bug

#417 Add Qt5 support
  HEN_HOUSE/egs++/view/clippingplanes.cpp
  HEN_HOUSE/egs++/view/main.cpp
  HEN_HOUSE/egs++/view/view.pro
  HEN_HOUSE/gui/egs_configure/egs_beam_install.pro
  HEN_HOUSE/gui/egs_configure/egs_install_env.cpp
  HEN_HOUSE/gui/egs_configure/egs_wizard.cpp
  HEN_HOUSE/gui/egs_configure/egs_wizard.h
  HEN_HOUSE/gui/egs_gui/egs_compile_page.cpp
  HEN_HOUSE/gui/egs_gui/egs_compile_page.h
  HEN_HOUSE/gui/egs_gui/egs_configuration_page.cpp
  HEN_HOUSE/gui/egs_gui/egs_configuration_page.h
  HEN_HOUSE/gui/egs_gui/egs_gui.pro
  HEN_HOUSE/gui/egs_gui/egs_gui_widget.cpp
  HEN_HOUSE/gui/egs_gui/egs_gui_widget.h
  HEN_HOUSE/gui/egs_gui/egs_run_page.cpp
  HEN_HOUSE/gui/egs_gui/egs_run_page.h
  HEN_HOUSE/gui/egs_gui/main.cpp
  HEN_HOUSE/gui/egs_gui/main_widget.cpp
  HEN_HOUSE/gui/egs_gui/main_widget.h
  HEN_HOUSE/gui/egs_gui/pegs_page.cpp
  HEN_HOUSE/gui/egs_inprz/egs_inprz.pro
  HEN_HOUSE/gui/egs_inprz/include/comboboxtooltip.h
  HEN_HOUSE/gui/egs_inprz/include/executiondlgImpl.h
  HEN_HOUSE/gui/egs_inprz/include/inputRZImpl.h
  HEN_HOUSE/gui/egs_inprz/include/tools.h
  HEN_HOUSE/gui/egs_inprz/src/comboboxtooltip.cpp
  HEN_HOUSE/gui/egs_inprz/src/eventfilter.cpp
  HEN_HOUSE/gui/egs_inprz/src/executiondlgImpl.cpp
  HEN_HOUSE/gui/egs_inprz/src/inputRZForm.cpp
  HEN_HOUSE/gui/egs_inprz/src/inputRZImpl.cpp
  HEN_HOUSE/gui/egs_inprz/src/mainRZ.cpp
  HEN_HOUSE/specs/windows.spec
Labels: compilation

#407 Add support for fish shell
  HEN_HOUSE/scripts/egsnrc_fishrc_additions
  HEN_HOUSE/scripts/finalize_egs_foruser
Labels: enhancement

#426 Fix #425: irold not updated in electron step loop
  HEN_HOUSE/src/egsnrc.mortran
Labels: bug, critical
