Repository nrc-cnrc/EGSnrc, pull requests merged in 2018-10, with the labels that each got.

#479 Add a flag to specify if EM fields are on or off
  HEN_HOUSE/egs++/egs_advanced_application.cpp
  HEN_HOUSE/interface/egs_interface2.h
  HEN_HOUSE/src/egs_utilities.mortran
  HEN_HOUSE/src/egsnrc.macros
  HEN_HOUSE/src/egsnrc.mortran
  HEN_HOUSE/src/emf_macros.mortran
  HEN_HOUSE/src/get_inputs.mortran
Labels: enhancement

#483 Fix #176: relax C compiler selection and conf name
  HEN_HOUSE/scripts/configure
  HEN_HOUSE/scripts/configure.expect
Labels: installation

#418 Add egs_phsp_scoring ausgab object.
  HEN_HOUSE/egs++/Makefile
  HEN_HOUSE/egs++/ausgab_objects/egs_phsp_scoring/Makefile
  HEN_HOUSE/egs++/ausgab_objects/egs_phsp_scoring/egs_phsp_scoring.cpp
  HEN_HOUSE/egs++/ausgab_objects/egs_phsp_scoring/egs_phsp_scoring.h
  HEN_HOUSE/egs++/egs_advanced_application.cpp
  HEN_HOUSE/egs++/egs_advanced_application.h
  HEN_HOUSE/egs++/egs_application.h
  HEN_HOUSE/iaea_phsp/iaea_header.cpp
Labels: enhancement

#482 Fix bug in atomic relaxation of some actinides
  HEN_HOUSE/src/egsnrc.macros
  HEN_HOUSE/src/egsnrc.mortran
Labels: bug

#480 Update I of BEAMnrc Users Manual
  HEN_HOUSE/doc/src/irs.bib
  HEN_HOUSE/doc/src/pirs509a-beamnrc/figures/hen_house.fig
  HEN_HOUSE/doc/src/pirs509a-beamnrc/figures/hen_house.pdf
  HEN_HOUSE/doc/src/pirs509a-beamnrc/figures/mortjob-mortran.fig
  HEN_HOUSE/doc/src/pirs509a-beamnrc/figures/mortjob-mortran.pdf
  HEN_HOUSE/doc/src/pirs509a-beamnrc/figures/nrc_users_area.fig
  HEN_HOUSE/doc/src/pirs509a-beamnrc/figures/nrc_users_area.pdf
  HEN_HOUSE/doc/src/pirs509a-beamnrc/figures/omega_home.fig
  HEN_HOUSE/doc/src/pirs509a-beamnrc/figures/omega_home.pdf
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/BEAM0.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/BEAM13.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/BEAM14.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/BEAM15.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/BEAM2.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/BEAM21.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/BEAM24.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/BEAM25.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/BEAM26.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/BEAM27.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/BEAM28.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/BEAM29.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/BEAM31.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/BEAM33.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/BEAM34.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/BEAM5.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/update.sh
  HEN_HOUSE/doc/src/pirs509a-beamnrc/pirs509a-beamnrc.tex
  HEN_HOUSE/omega/beamnrc/beamnrc.mortran
  HEN_HOUSE/omega/progs/gui/beamnrc/beamnrc_params.tcl
  HEN_HOUSE/specs/beamnrc.spec
  HEN_HOUSE/src/get_inputs.mortran
Labels: documentation

#484 Fix #443: SYNCHDMLC zmin output and gui checks
  HEN_HOUSE/omega/beamnrc/CMs/SYNCHDMLC_cm.mortran
  HEN_HOUSE/omega/progs/gui/beamnrc/synchdmlc.tcl
Labels: bug

#386 Add radionuclide source refinements (collimated source, experiment time ...)
  HEN_HOUSE/egs++/egs_base_source.h
  HEN_HOUSE/egs++/egs_spectra.cpp
  HEN_HOUSE/egs++/sources/egs_radionuclide_source/egs_radionuclide_source.cpp
  HEN_HOUSE/egs++/sources/egs_radionuclide_source/egs_radionuclide_source.h
Labels: enhancement

#481 Add a simple template egs++ application egs_app
  HEN_HOUSE/scripts/finalize_egs_foruser
  HEN_HOUSE/user_codes/egs_app/Makefile
  HEN_HOUSE/user_codes/egs_app/array_sizes.h
  HEN_HOUSE/user_codes/egs_app/egs_app.cpp
  HEN_HOUSE/user_codes/egs_app/slab.egsinp
Labels: enhancement
