Repository nrc-cnrc/EGSnrc, pull requests merged in 2018-08, with the labels that each got.

#427 Update egs_view layout
  HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.h
  HEN_HOUSE/egs++/egs_base_geometry.cpp
  HEN_HOUSE/egs++/egs_base_geometry.h
  HEN_HOUSE/egs++/sources/egs_fano_source/egs_fano_source.h
  HEN_HOUSE/egs++/view/clippingplanes.cpp
  HEN_HOUSE/egs++/view/clippingplanes.h
  HEN_HOUSE/egs++/view/clippingplanes.ui
  HEN_HOUSE/egs++/view/egs_track_view.cpp
  HEN_HOUSE/egs++/view/egs_track_view.h
  HEN_HOUSE/egs++/view/egs_visualizer.cpp
  HEN_HOUSE/egs++/view/egs_visualizer.h
  HEN_HOUSE/egs++/view/image_window.cpp
  HEN_HOUSE/egs++/view/image_window.h
  HEN_HOUSE/egs++/view/main.cpp
  HEN_HOUSE/egs++/view/renderworker.cpp
  HEN_HOUSE/egs++/view/renderworker.h
  HEN_HOUSE/egs++/view/view.pro
  HEN_HOUSE/egs++/view/viewcontrol.cpp
  HEN_HOUSE/egs++/view/viewcontrol.h
  HEN_HOUSE/egs++/view/viewcontrol.ui
Labels: bug, enhancement

#440 Fix Qt GUI compile functions and tooltip
  HEN_HOUSE/gui/egs_gui/egs_compile_page.cpp
  HEN_HOUSE/gui/egs_inprz/src/inputRZForm.cpp
  HEN_HOUSE/gui/egs_inprz/src/inputRZImpl.cpp
Labels: bug

#452 Fix #359: photon cs parameter not initialized
  HEN_HOUSE/src/get_inputs.mortran
Labels: bug

#472 Radiative splitting ausgab object (AO)
  HEN_HOUSE/egs++/Makefile
  HEN_HOUSE/egs++/ausgab_objects/egs_radiative_splitting/Makefile
  HEN_HOUSE/egs++/ausgab_objects/egs_radiative_splitting/egs_radiative_splitting.cpp
  HEN_HOUSE/egs++/ausgab_objects/egs_radiative_splitting/egs_radiative_splitting.h
  HEN_HOUSE/egs++/egs_advanced_application.cpp
  HEN_HOUSE/egs++/egs_advanced_application.h
  HEN_HOUSE/egs++/egs_application.h
Labels: enhancement
