Repository nrc-cnrc/EGSnrc, pull requests merged in 2018-09, with the labels that each got.

#445 Fix length of text line in get_media_inputs.mortran
  HEN_HOUSE/src/get_media_inputs.mortran
Labels: bug

#434 Fix #430: Fix blank inputs for DOSXYZnrc sources
  HEN_HOUSE/user_codes/dosxyznrc/srcxyznrc.mortran
Labels: bug

#450 Fix #437: Prevent call to vcusource from overwriting zsrc.
  HEN_HOUSE/user_codes/dosxyznrc/srcxyznrc.mortran
Labels: bug

#465 Fix egs_prism number of regions set to zero
  HEN_HOUSE/egs++/geometry/egs_planes/egs_planes.cpp
  HEN_HOUSE/egs++/geometry/egs_prism/egs_prism.h
  HEN_HOUSE/egs++/geometry/egs_pyramid/egs_pyramid.cpp
Labels: bug

#460 Fix predefined data for SSB media in pegsless mode.
  HEN_HOUSE/src/pegs4_macros.mortran
Labels: bug

#457 Fix #447: Fix parallel runs with beam sim. source using phase space
  HEN_HOUSE/cutils/load_beamlib.c
  HEN_HOUSE/egs++/sources/egs_beam_source/egs_beam_source.cpp
  HEN_HOUSE/egs++/sources/egs_beam_source/egs_beam_source.h
  HEN_HOUSE/omega/beamnrc/beam_lib.mortran
  HEN_HOUSE/omega/beamnrc/beamnrc.mortran
  HEN_HOUSE/omega/beamnrc/beamnrc_user_macros.mortran
  HEN_HOUSE/user_codes/dosxyznrc/srcxyznrc.mortran
  HEN_HOUSE/utils/srcrz.mortran
Labels: bug

#476 Fix egs_view simulation geometry selection
  HEN_HOUSE/egs++/geometry/egs_cylinders/egs_cylinders.cpp
  HEN_HOUSE/egs++/view/renderworker.cpp
  HEN_HOUSE/egs++/view/viewcontrol.cpp
  HEN_HOUSE/egs++/view/viewcontrol.h
Labels: bug

#435 Fix #424: Add clean option to IAEA Makefile.
  HEN_HOUSE/iaea_phsp/Makefile
Labels: compilation, enhancement

#436 Fix #409: Relax input format for .egsphant dimensions.
  HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc.mortran
Labels: enhancement

#453 Fix DSB help dialog in beamnrc_gui
  HEN_HOUSE/omega/progs/gui/beamnrc/help.tcl
Labels: documentation

#463 Fix #419: IAUSFL not initialized for new ausgab values
  HEN_HOUSE/omega/beamnrc/beamnrc.mortran
  HEN_HOUSE/user_codes/cavrznrc/cavrznrc.mortran
  HEN_HOUSE/user_codes/cavsphnrc/cavsphnrc.mortran
  HEN_HOUSE/user_codes/dosrznrc/dosrznrc.mortran
  HEN_HOUSE/user_codes/flurznrc/flurznrc.mortran
  HEN_HOUSE/user_codes/sprrznrc/sprrznrc.mortran
Labels: enhancement

#428 Add a getting-started manual
  HEN_HOUSE/doc/src/Makefile
  HEN_HOUSE/doc/src/getting-started/figures/3C.png
  HEN_HOUSE/doc/src/getting-started/figures/LICENCE.md
  HEN_HOUSE/doc/src/getting-started/figures/README.md
  HEN_HOUSE/doc/src/getting-started/figures/Users_EGSnrc_area.png
  HEN_HOUSE/doc/src/getting-started/figures/a12.png
  HEN_HOUSE/doc/src/getting-started/figures/a12view.png
  HEN_HOUSE/doc/src/getting-started/figures/beamdp_step1.png
  HEN_HOUSE/doc/src/getting-started/figures/beamdp_step2.png
  HEN_HOUSE/doc/src/getting-started/figures/beamdp_step3.png
  HEN_HOUSE/doc/src/getting-started/figures/beamnrc_compile.png
  HEN_HOUSE/doc/src/getting-started/figures/beamnrc_main.png
  HEN_HOUSE/doc/src/getting-started/figures/beamnrc_scoring.png
  HEN_HOUSE/doc/src/getting-started/figures/beamnrc_source1.png
  HEN_HOUSE/doc/src/getting-started/figures/beamnrc_specifyNew.png
  HEN_HOUSE/doc/src/getting-started/figures/beamnrc_specifyNew2.png
  HEN_HOUSE/doc/src/getting-started/figures/beamnrc_specifyNew3.png
  HEN_HOUSE/doc/src/getting-started/figures/beamnrc_syncjaws.png
  HEN_HOUSE/doc/src/getting-started/figures/box.png
  HEN_HOUSE/doc/src/getting-started/figures/dosxyz_show.png
  HEN_HOUSE/doc/src/getting-started/figures/dosxyz_step1.png
  HEN_HOUSE/doc/src/getting-started/figures/dosxyz_step2.png
  HEN_HOUSE/doc/src/getting-started/figures/dosxyz_step3.png
  HEN_HOUSE/doc/src/getting-started/figures/egsApplications.png
  HEN_HOUSE/doc/src/getting-started/figures/egs_file_structure_with_egspp.pdf
  HEN_HOUSE/doc/src/getting-started/figures/spheres.png
  HEN_HOUSE/doc/src/getting-started/figures/statdose_profile.png
  HEN_HOUSE/doc/src/getting-started/figures/ta-plate-example.png
  HEN_HOUSE/doc/src/getting-started/getting-started.tex
  HEN_HOUSE/doc/src/pirs898-egs++/Doxyfile
  HEN_HOUSE/doc/src/pirs898-egs++/cavity.doxy
  HEN_HOUSE/doc/src/pirs898-egs++/common.doxy
  HEN_HOUSE/doc/src/pirs898-egs++/egs_chamber.doxy
  HEN_HOUSE/doc/src/pirs898-egs++/egs_fac.doxy
  HEN_HOUSE/doc/src/pirs898-egs++/geometry.doxy
  HEN_HOUSE/egs++/egs_simple_application.h
Labels: documentation

#455 Fix synchdmlc dimension check and medium bugs
  HEN_HOUSE/doc/src/pirs509a-beamnrc/figures/synchdmlcd.fig
  HEN_HOUSE/doc/src/pirs509a-beamnrc/figures/synchdmlcd.pdf
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/SYNCHDMLC.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/pirs509a-beamnrc.tex
  HEN_HOUSE/omega/beamnrc/CMs/SYNCHDMLC_cm.mortran
  HEN_HOUSE/omega/progs/gui/beamnrc/beamnrc_params.tcl
  HEN_HOUSE/omega/progs/gui/beamnrc/graphics/help_dynvmlc_tar.fig
  HEN_HOUSE/omega/progs/gui/beamnrc/graphics/help_dynvmlc_tar.gif
  HEN_HOUSE/omega/progs/gui/beamnrc/graphics/help_synchdmlc.gif
  HEN_HOUSE/omega/progs/gui/beamnrc/misc_egsnrc.tcl
  HEN_HOUSE/omega/progs/gui/beamnrc/synchdmlc.tcl
Labels: bug

#432 Fix #423: change -ffast-math to -mtune=native
  HEN_HOUSE/doc/src/pirs509a-beamnrc/pirs509a-beamnrc.tex
  HEN_HOUSE/doc/src/pirs702-egsnrc-codes/pirs702-egsnrc-codes.tex
  HEN_HOUSE/doc/src/pirs794-dosxyznrc/pirs794-dosxyznrc.tex
  HEN_HOUSE/gui/egs_configure/egs_tools.cpp
  HEN_HOUSE/scripts/configure
  HEN_HOUSE/scripts/configure_c++
Labels: compilation, installation
