Repository nrc-cnrc/EGSnrc, pull requests merged in 2019-03, with the labels that each got.

#509 Fix windows compilation bug
  HEN_HOUSE/egs++/Makefile
  HEN_HOUSE/egs++/ausgab_objects/egs_radiative_splitting/Makefile
  HEN_HOUSE/egs++/egs_ensdf.h
Labels: bug, compilation

#508 Fix Win egs_system function
  HEN_HOUSE/gui/egs_configure/egs_tools.cpp
  HEN_HOUSE/pieces/tests_win.xml
Labels: bug, installation

#510 Fix #485: string size mismatch in media inputs
  HEN_HOUSE/src/egsnrc.macros
  HEN_HOUSE/src/get_inputs.mortran
Labels: bug

#516 Fix egs_view compilation
  HEN_HOUSE/egs++/view/viewcontrol.ui
Labels: bug, compilation

#515 Update egs_view references in the docs
  HEN_HOUSE/doc/src/getting-started/getting-started.tex
  HEN_HOUSE/doc/src/pirs898-egs++/Doxyfile
  HEN_HOUSE/doc/src/pirs898-egs++/figures/clipping.png
  HEN_HOUSE/doc/src/pirs898-egs++/figures/egs_view1.png
  HEN_HOUSE/doc/src/pirs898-egs++/figures/egs_view2.png
  HEN_HOUSE/doc/src/pirs898-egs++/figures/egs_view3.png
  HEN_HOUSE/doc/src/pirs898-egs++/figures/egs_view4.png
  HEN_HOUSE/doc/src/pirs898-egs++/figures/view_controls.png
  HEN_HOUSE/doc/src/pirs898-egs++/geometry.doxy
Labels: documentation

#496 Fix radionuclide source emission bugs
  HEN_HOUSE/egs++/egs_ensdf.cpp
  HEN_HOUSE/egs++/egs_ensdf.h
  HEN_HOUSE/egs++/egs_spectra.cpp
  HEN_HOUSE/egs++/sources/egs_radionuclide_source/egs_radionuclide_source.cpp
  HEN_HOUSE/egs++/sources/egs_radionuclide_source/egs_radionuclide_source.h
  HEN_HOUSE/spectra/lnhb/ensdf/Th-234.txt
Labels: bug, enhancement

#462 Fix #388, #383: concave CD, XYZ inside CD, conestack, and box geometry errors
  HEN_HOUSE/egs++/egs_base_geometry.cpp
  HEN_HOUSE/egs++/egs_base_geometry.h
  HEN_HOUSE/egs++/geometry/egs_box/egs_box.h
  HEN_HOUSE/egs++/geometry/egs_cd_geometry/egs_cd_geometry.h
  HEN_HOUSE/egs++/geometry/egs_cones/egs_cones.h
  HEN_HOUSE/egs++/geometry/egs_cylinders/egs_cylinders.h
  HEN_HOUSE/egs++/geometry/egs_nd_geometry/egs_nd_geometry.h
  HEN_HOUSE/egs++/geometry/egs_spheres/egs_spheres.cpp
Labels: bug

#517 Fix egs_inputs line length
  HEN_HOUSE/src/get_inputs.mortran
Labels: bug
