Repository nrc-cnrc/EGSnrc, pull requests merged in 2020-08, with the labels that each got.

#620 Fix #607: Bug in sprrznrc output of D/Dmax
  HEN_HOUSE/user_codes/sprrznrc/sprrznrc.mortran
Labels: bug

#619 Fix #616: Space in group name crashes configure script
  HEN_HOUSE/scripts/configure
Labels: bug, installation

#621 Fix minor bug in DOSRZnrc kerma calculation
  HEN_HOUSE/user_codes/dosrznrc/dosrznrc.mortran
Labels: bug

#618 Fix #608: Typo in DOSXYZnrc PCUT input check
  HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc.mortran
Labels: bug

#617 Fix #612: Throw error for C>=1 in dosrznrc
  HEN_HOUSE/user_codes/dosrznrc/dosrznrc.mortran
Labels: bug

#615 Fix the addphsp usage text
  HEN_HOUSE/omega/progs/addphsp/addphsp.mortran
Labels: documentation

#610 Fix egs_kerma FD bugs and expand its capabilities
  HEN_HOUSE/doc/src/pirs898-egs++/Doxyfile
  HEN_HOUSE/doc/src/pirs898-egs++/cavity.doxy
  HEN_HOUSE/doc/src/pirs898-egs++/egs_cbct.doxy
  HEN_HOUSE/doc/src/pirs898-egs++/egs_chamber.doxy
  HEN_HOUSE/doc/src/pirs898-egs++/egs_fac.doxy
  HEN_HOUSE/doc/src/pirs898-egs++/egs_kerma.doxy
  HEN_HOUSE/user_codes/egs_kerma/egs_kerma.cpp
  HEN_HOUSE/user_codes/egs_kerma/emuen_rho_air_1keV-1.5MeV.data
  HEN_HOUSE/user_codes/egs_kerma/emuen_rho_air_1keV-20MeV.data
  HEN_HOUSE/user_codes/egs_kerma/emuen_rho_water_1keV-1.5MeV.data
  HEN_HOUSE/user_codes/egs_kerma/example_20MeV_e-_Pb-shield_FD.egsinp
  HEN_HOUSE/user_codes/egs_kerma/example_40keV_SDD_1m_FD.egsinp
  HEN_HOUSE/user_codes/egs_kerma/example_5keV_H2O_FD.egsinp
Labels: bug, documentation, enhancement

#586 Fix CHAMBER dose zone numbering
  HEN_HOUSE/omega/beamnrc/CMs/CHAMBER_cm.mortran
  HEN_HOUSE/omega/beamnrc/beamnrc.mortran
Labels: bug

#595 Label fluorescent photons from eii as secondary.
  HEN_HOUSE/omega/beamnrc/beamnrc.mortran
Labels: bug

#600 Feature expand environment variable in file names for C++ apps
  HEN_HOUSE/egs++/egs_functions.cpp
  HEN_HOUSE/egs++/egs_functions.h
  HEN_HOUSE/egs++/egs_spectra.cpp
  HEN_HOUSE/user_codes/cavity/cavity.cpp
  HEN_HOUSE/user_codes/egs_cbct/egs_cbct.cpp
  HEN_HOUSE/user_codes/egs_cbct/example_w5br.egsinp
  HEN_HOUSE/user_codes/egs_fac/egs_fac.cpp
  HEN_HOUSE/user_codes/egs_fac/examples/example_mees_250kV.egsinp
  HEN_HOUSE/user_codes/egs_fac/examples/mxr-320-250kVp_tube.egsinp
  HEN_HOUSE/user_codes/egs_kerma/egs_kerma.cpp
  HEN_HOUSE/user_codes/egs_kerma/example_40keV_SDD_1m_FD.egsinp
Labels: enhancement

#589 Increase MXSTACK for relevant apps
  HEN_HOUSE/omega/beamnrc/beamnrc_user_macros.mortran
  HEN_HOUSE/user_codes/cavity/array_sizes.h
  HEN_HOUSE/user_codes/cavrznrc/cavrznrc.mortran
  HEN_HOUSE/user_codes/cavsphnrc/cavsphnrc.mortran
  HEN_HOUSE/user_codes/dosrznrc/dosrznrc.mortran
  HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc_user_macros.mortran
  HEN_HOUSE/user_codes/egs_app/array_sizes.h
  HEN_HOUSE/user_codes/egs_chamber/array_sizes.h
  HEN_HOUSE/user_codes/egs_fac/array_sizes.h
  HEN_HOUSE/user_codes/flurznrc/flurznrc.mortran
Labels: enhancement

#583 Fix file includes in egs++ input files
  HEN_HOUSE/egs++/egs_input.cpp
Labels: bug

#579 Fix the egs_chamber region-specific ECUT check
  HEN_HOUSE/user_codes/egs_chamber/egs_chamber.cpp
Labels: bug

#499 Complex lock file locking for issue #438
  HEN_HOUSE/cutils/egs_c_utils.c
Labels: enhancement

#576 Fix an egs_configure compilation error on Windows
  HEN_HOUSE/gui/egs_configure/egs_tools.cpp
Labels: compilation
