Repository nrc-cnrc/EGSnrc, pull requests merged in 2020-01, with the labels that each got.

#568 Fix tracks crashing egs_view in Windows
  HEN_HOUSE/egs++/view/egs_track_view.cpp
  HEN_HOUSE/egs++/view/viewcontrol.cpp
Labels: bug

#503 Fix #478: Fix search delimiters in medium data file.
  HEN_HOUSE/src/get_inputs.mortran
  HEN_HOUSE/src/get_media_inputs.mortran
Labels: bug

#567 Change two variable names in DOSRZnrc
  HEN_HOUSE/user_codes/dosrznrc/dosrznrc.mortran
Labels: documentation

#514 Fix #489: Allow odd no. of TARGET/ISOCENTER leaves in SYNCHDMLC
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/SYNCHDMLC.inp
  HEN_HOUSE/doc/src/pirs509a-beamnrc/pirs509a-beamnrc.tex
  HEN_HOUSE/omega/beamnrc/CMs/SYNCHDMLC_cm.mortran
  HEN_HOUSE/omega/progs/gui/beamnrc/beamnrc_params.tcl
  HEN_HOUSE/omega/progs/gui/beamnrc/synchdmlc.tcl
Labels: bug

#520 Fix #497: Fix check on WRAILBOT for TARGET leaves.
  HEN_HOUSE/doc/src/pirs509a-beamnrc/figures/dynvmlcd.fig
  HEN_HOUSE/doc/src/pirs509a-beamnrc/figures/dynvmlcd.pdf
  HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/DYNVMLC.inp
  HEN_HOUSE/omega/beamnrc/CMs/DYNVMLC_cm.mortran
  HEN_HOUSE/omega/beamnrc/CMs/SYNCHDMLC_cm.mortran
  HEN_HOUSE/omega/beamnrc/CMs/SYNCVMLC_cm.mortran
  HEN_HOUSE/omega/progs/gui/beamnrc/dynvmlc.tcl
  HEN_HOUSE/omega/progs/gui/beamnrc/graphics/help_dynvmlc.gif
  HEN_HOUSE/omega/progs/gui/beamnrc/graphics/help_syncvmlc.gif
  HEN_HOUSE/omega/progs/gui/beamnrc/synchdmlc.tcl
  HEN_HOUSE/omega/progs/gui/beamnrc/syncvmlc.tcl
Labels: bug

#525 Fix #522: More robust rotation checking in egs++ transformations
  HEN_HOUSE/egs++/egs_transformations.h
Labels: enhancement

#547 Fix #9: Increase array defaults, decrease EPSEMFP
  HEN_HOUSE/omega/beamnrc/CMs/BLOCK_macros.mortran
  HEN_HOUSE/omega/beamnrc/CMs/SYNCHDMLC_macros.mortran
  HEN_HOUSE/omega/beamnrc/CMs/SYNCJAWS_macros.mortran
  HEN_HOUSE/omega/beamnrc/CMs/SYNCMLCE_macros.mortran
  HEN_HOUSE/omega/beamnrc/CMs/SYNCVMLC_macros.mortran
  HEN_HOUSE/omega/progs/statdose/statdose.mortran
  HEN_HOUSE/src/egsnrc.macros
  HEN_HOUSE/user_codes/cavity/array_sizes.h
  HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc_user_macros.mortran
  HEN_HOUSE/user_codes/egs_fac/array_sizes.h
  HEN_HOUSE/user_codes/tutor7pp/array_sizes.h
Labels: enhancement

#565 Fix #554: Compile error when BEAMnrc EEMF macros are used
  HEN_HOUSE/src/EEMF_macros.mortran
  HEN_HOUSE/src/EEMF_macros_beamnrc.mortran
Labels: compilation

#557 Fix source collection and simple alias table
  HEN_HOUSE/egs++/egs_alias_table.cpp
  HEN_HOUSE/egs++/egs_alias_table.h
  HEN_HOUSE/egs++/sources/egs_source_collection/egs_source_collection.h
Labels: bug, critical

#531 Fix geometry errors for prism and XYZ in a CD
  HEN_HOUSE/egs++/egs_polygon.h
  HEN_HOUSE/egs++/geometry/egs_nd_geometry/egs_nd_geometry.h
  HEN_HOUSE/egs++/geometry/egs_prism/egs_prism.h
Labels: bug

#572 add egs_fano_source to egs++ Makefile
  HEN_HOUSE/egs++/Makefile
Labels: compilation

#575 Fix glib and egs_rz windows compilation
  HEN_HOUSE/egs++/geometry/egs_autoenvelope/Makefile
  HEN_HOUSE/egs++/geometry/egs_glib/Makefile
  HEN_HOUSE/egs++/geometry/egs_rz/Makefile
Labels: compilation
