Repository nrc-cnrc/EGSnrc, pull requests merged in 2021-03, with the labels that each got.

#653 Fix command to get file size in configure script
  HEN_HOUSE/scripts/configure
Labels: bug, compilation, critical

#667 Flag Rayleigh photons as scattered in dosrznrc
  HEN_HOUSE/user_codes/dosrznrc/dosrznrc.mortran
Labels: bug, critical

#666 Fix bug in precision goal in g and 1 keV round-off
  HEN_HOUSE/src/egsnrc.macros
  HEN_HOUSE/user_codes/g/g.mortran
Labels: bug, critical

#648 Fix pegs4 compilation errors for gcc > 10.0
  HEN_HOUSE/pegs4/Makefile
  HEN_HOUSE/pegs4/pegs4.mortran
Labels: bug, compilation, critical, installation

#645 Fix the dose values in egs++ 3ddose output
  HEN_HOUSE/egs++/egs_base_geometry.h
  HEN_HOUSE/egs++/geometry/egs_nd_geometry/egs_nd_geometry.cpp
  HEN_HOUSE/egs++/geometry/egs_nd_geometry/egs_nd_geometry.h
Labels: bug, critical

#638 Fix a typo that made EEMF fail to compile
  HEN_HOUSE/src/EEMF_macros.mortran
  HEN_HOUSE/src/EEMF_macros_beamnrc.mortran
Labels: bug, compilation

#560 Reduce machine epsilon and add a distance epsilon
  HEN_HOUSE/egs++/egs_base_geometry.cpp
  HEN_HOUSE/egs++/egs_functions.h
Labels: enhancement

#636 Fix dosxyz_gui help text for phsp output
  HEN_HOUSE/omega/progs/gui/dosxyznrc/set_main_inputs_egsnrc.tcl
  HEN_HOUSE/omega/progs/gui/dosxyznrc/xyznrc_parameters.tcl
Labels: documentation

#492 Add a spectrum scoring application egs_phd
  HEN_HOUSE/pegs4/density_corrections/compounds/cellulose.density
  HEN_HOUSE/pegs4/density_corrections/compounds/silicondioxide_1.4g_cm3.density
  HEN_HOUSE/scripts/finalize_egs_foruser
  HEN_HOUSE/user_codes/egs_phd/Makefile
  HEN_HOUSE/user_codes/egs_phd/array_sizes.h
  HEN_HOUSE/user_codes/egs_phd/egs_phd.cpp
  HEN_HOUSE/user_codes/egs_phd/egs_phd.h
  HEN_HOUSE/user_codes/egs_phd/ge-example.egsinp
  HEN_HOUSE/user_codes/egs_phd/ge-example.egsview
  HEN_HOUSE/user_codes/egs_phd/ge-example.png
  HEN_HOUSE/user_codes/egs_phd/icrm-hpge-example.egsinp
Labels: enhancement

#643 Set $EGS_HOME & $HEN_HOUSE for egs++ beam sources
  HEN_HOUSE/egs++/sources/egs_beam_source/egs_beam_source.cpp
Labels: enhancement

#592 Add egs_circle_perpendicular shape
  HEN_HOUSE/egs++/Makefile
  HEN_HOUSE/egs++/shapes/egs_circle_perpendicular/Makefile
  HEN_HOUSE/egs++/shapes/egs_circle_perpendicular/egs_circle_perpendicular.cpp
  HEN_HOUSE/egs++/shapes/egs_circle_perpendicular/egs_circle_perpendicular.h
Labels: enhancement

#631 Add code owners file to automate review requests
  .github/CODEOWNERS
Labels: admin

#662 Fix phsp output with photon splitting
  HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc.mortran
Labels: bug
