Repository nrc-cnrc/EGSnrc, pull requests merged in 2022-07, with the labels that each got.

#878 Fix BEAMnrc synchdmlc component module bugs
  HEN_HOUSE/doc/src/pirs509a-beamnrc/figures/synchdmlcd.fig
  HEN_HOUSE/doc/src/pirs509a-beamnrc/figures/synchdmlcd.pdf
  HEN_HOUSE/doc/src/pirs509a-beamnrc/pirs509a-beamnrc.tex
  HEN_HOUSE/omega/beamnrc/CMs/SYNCHDMLC_cm.mortran
  HEN_HOUSE/omega/beamnrc/CMs/SYNCHDMLC_macros.mortran
  HEN_HOUSE/omega/progs/gui/beamnrc/synchdmlc.tcl
Labels: bug, improvement

#721 Add the dirt density file used by icrm-hpge-example
  HEN_HOUSE/pegs4/density_corrections/compounds/cellulose.density
  HEN_HOUSE/pegs4/density_corrections/compounds/silicondioxide_1.4g_cm3.density
  HEN_HOUSE/user_codes/egs_phd/icrm-hpge-example.egsinp
Labels: documentation

#899 Add checks for gcc version when setting the default c++ standard
  HEN_HOUSE/egs++/view/view.pro
  HEN_HOUSE/gui/egs_configure/egs_tools.cpp
  HEN_HOUSE/scripts/configure_c++
Labels: installation, compilation

#898 Fix git branch logging and egs_home vs HEN_HOUSE code comparisons
  HEN_HOUSE/gui/egs_configure/egs_install.h
  HEN_HOUSE/makefiles/cpp_makefile
  HEN_HOUSE/makefiles/standard_makefile
  HEN_HOUSE/specs/all_common.spec
  HEN_HOUSE/src/egs_utilities.mortran
Labels: cleanup

#896 Use position/direction sampling from base source for radionuclide sources
  HEN_HOUSE/egs++/sources/egs_radionuclide_source/egs_radionuclide_source.cpp
  HEN_HOUSE/egs++/sources/egs_radionuclide_source/egs_radionuclide_source.h
Labels: improvement

#905 Fix #904: avoid gcc -mcmodel flag on macos systems
  HEN_HOUSE/scripts/configure
  HEN_HOUSE/scripts/configure_c++
Labels: bug, compilation, macos

#405 Option: output sparse binary dose file instead of 3ddose in DOSXYZnrc
  HEN_HOUSE/doc/src/pirs794-dosxyznrc/inputs/dosxyznrc.inp
  HEN_HOUSE/doc/src/pirs794-dosxyznrc/pirs794-dosxyznrc.tex
  HEN_HOUSE/omega/progs/gui/dosxyznrc/create_file_nrc.tcl
  HEN_HOUSE/omega/progs/gui/dosxyznrc/load_input2_nrc.tcl
  HEN_HOUSE/omega/progs/gui/dosxyznrc/reset_parameters_nrc.tcl
  HEN_HOUSE/omega/progs/gui/dosxyznrc/set_main_inputs_egsnrc.tcl
  HEN_HOUSE/omega/progs/gui/dosxyznrc/xyznrc_parameters.tcl
  HEN_HOUSE/src/egs_utilities.mortran
  HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc.mortran
Labels: improvement
