Repository nrc-cnrc/EGSnrc, pull requests merged in 2022-06, with the labels that each got.

#714 Fix g bug: SEGFAULT when using spectrum
  HEN_HOUSE/user_codes/g/g.mortran
Labels: bug, critical

#864 Fix buffer overflow from scoring bin rounding
  HEN_HOUSE/user_codes/tutor7pp/tutor7pp.cpp
Labels: bug

#829 Check that ir is not -1 for region dose scoring
  HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.h
Labels: bug

#877 Document NRC brems cross section option
  HEN_HOUSE/doc/src/pirs898-egs++/common.doxy
  HEN_HOUSE/interface/egs_interface2.h
Labels: documentation

#845 Fix serious bug in MCDF-XCOM PE routine
  HEN_HOUSE/src/egsnrc.mortran
Labels: bug, critical

#713 Increase the list of colours for the BEAMnrc gui
  HEN_HOUSE/omega/progs/gui/beamnrc/beamnrc_gui.tcl
Labels: improvement, small

#414 Add git hash, branch and compile time to egs++ output
  HEN_HOUSE/gui/egs_configure/egs_install.h
  HEN_HOUSE/gui/egs_configure/egs_install_conf.cpp
  HEN_HOUSE/makefiles/cpp_makefile
  HEN_HOUSE/makefiles/standard_makefile
  HEN_HOUSE/scripts/configure
  HEN_HOUSE/specs/all_common.spec
  HEN_HOUSE/src/egs_utilities.mortran
  HEN_HOUSE/src/egsnrc.macros
Labels: improvement, installation, small

#751 Guard against more than one track_scoring object in egsinp
  HEN_HOUSE/egs++/egs_application.cpp
Labels: bug, small

#756 Fix out-of-bounds read in `egs_view` by making region arrays the same size
  HEN_HOUSE/egs++/view/image_window.cpp
Labels: bug, small

#787 Fix a mistake in the getting-started solutions
  HEN_HOUSE/doc/src/getting-started/getting-started.tex
Labels: documentation, small

#794 Document egs++ rng definition block
  HEN_HOUSE/doc/src/pirs898-egs++/common.doxy
Labels: documentation, small

#806 Fix #803 a quiksyncdef error from DYNJAWS in BEAMnrc GUI
  HEN_HOUSE/omega/progs/gui/beamnrc/syncjaws.tcl
Labels: bug, gui, small

#729 Add check for maximum number of particles to addphsp
  HEN_HOUSE/omega/progs/addphsp/addphsp.mortran
Labels: bug, small

#717 Fix `ReadCT_DICOM()` to work with slices of arbitrary size
  HEN_HOUSE/omega/progs/ctcreate/ReadCT_DICOM.c
Labels: bug, small

#703 Update compiler flags to require c++14 standard
  HEN_HOUSE/egs++/view/view.pro
  HEN_HOUSE/gui/egs_configure/egs_tools.cpp
  HEN_HOUSE/scripts/configure_c++
Labels: improvement, compilation, small
