Repository nrc-cnrc/EGSnrc, pull requests merged in 2022-10, with the labels that each got.

#759 Fix egs++ 3ddose output and change getMass to getVolume
  HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.cpp
  HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.h
  HEN_HOUSE/egs++/egs_advanced_application.cpp
  HEN_HOUSE/egs++/egs_base_geometry.h
  HEN_HOUSE/egs++/geometry/egs_autoenvelope/egs_autoenvelope.cpp
  HEN_HOUSE/egs++/geometry/egs_autoenvelope/egs_autoenvelope.h
  HEN_HOUSE/egs++/geometry/egs_autoenvelope/volcor.h
  HEN_HOUSE/egs++/geometry/egs_nd_geometry/egs_nd_geometry.cpp
  HEN_HOUSE/egs++/geometry/egs_nd_geometry/egs_nd_geometry.h
  HEN_HOUSE/egs++/geometry/egs_rz/egs_rz.cpp
  HEN_HOUSE/egs++/geometry/egs_rz/egs_rz.h
  HEN_HOUSE/egs++/geometry/egs_spheres/egs_spheres.cpp
  HEN_HOUSE/egs++/geometry/egs_spheres/egs_spheres.h
Labels: bug, improvement, critical

#931 Fix mlce comment
  HEN_HOUSE/omega/beamnrc/CMs/MLCE_macros.mortran
Labels: compilation, small

#915 Fix logging of git hash and compile time for BEAMnrc
  HEN_HOUSE/makefiles/beam_makefile
  HEN_HOUSE/specs/beamnrc.spec
  HEN_HOUSE/src/egs_utilities.mortran
Labels: compilation

#908 Fix configure_c++ on macOS
  HEN_HOUSE/scripts/configure_c++
Labels: installation, macos

#895 Fix #894: revert egsphant to egs_brachy encoding
  HEN_HOUSE/omega/progs/ctcreate/ctcreate.mortran
  HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc.mortran
  HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc_user_macros.mortran
Labels: bug, improvement
