Repository nrc-cnrc/EGSnrc, pull requests merged in 2023-01, with the labels that each got.

#893 Fix various small issues ahead of release
  HEN_HOUSE/doc/src/pirs898-egs++/egs_cbct.doxy
  HEN_HOUSE/doc/src/pirs898-egs++/main.doxy
  HEN_HOUSE/egs++/egs_advanced_application.cpp
  HEN_HOUSE/egs++/egs_application.cpp
  HEN_HOUSE/egs++/egs_spectra.cpp
  HEN_HOUSE/egs++/geometry/egs_vhp_geometry/egs_vhp_geometry.cpp
  HEN_HOUSE/scripts/configure
  HEN_HOUSE/src/egsnrc.macros
  HEN_HOUSE/src/egsnrc.mortran
  HEN_HOUSE/user_codes/tutor7pp/tutor7pp.cpp
Labels: cleanup, small

#952 Fix #945, #804: egs_chamber examples don't run by default
  HEN_HOUSE/user_codes/egs_chamber/example1_co60_Pfactors.egsinp
  HEN_HOUSE/user_codes/egs_chamber/example1_profile_pfactors.egsinp
  HEN_HOUSE/user_codes/egs_chamber/example2_chamber_dd.egsinp
Labels: documentation

#954 Run astyle on egs++ before release
  HEN_HOUSE/egs++/geometry/egs_genvelope/egs_envelope_geometry.h
  HEN_HOUSE/egs++/sources/egs_radionuclide_source/egs_radionuclide_source.cpp
Labels: cleanup, small

#950 Fix #949: compiler errors of egs_mesh on mac
  HEN_HOUSE/egs++/geometry/egs_mesh/egs_mesh.h
Labels: compilation, small
