Repository nrc-cnrc/EGSnrc, pull requests merged in 2023-08, with the labels that each got.

#976 Update repo readme to remove reddit link
  README.md
Labels: documentation

#977 Update repo webpage to remove reddit link
  index.md
Labels: documentation

#979 Clarify egs_box example with explicit bounds
  HEN_HOUSE/egs++/geometry/egs_box/egs_box.h
Labels: improvement, documentation

#972 Fix compilation on windows for some time zones, add lquadmath
  HEN_HOUSE/gui/egs_configure/egs_tools.cpp
  HEN_HOUSE/scripts/configure
  HEN_HOUSE/specs/all_common.spec
  HEN_HOUSE/specs/beamnrc.spec
Labels: bug, compilation, windows
