Repository nrc-cnrc/EGSnrc, pull requests merged in 2024-09, with the labels that each got.

#1019 Fix #1018: Number of brems events miscounted for DBS in BEAMnrc
  HEN_HOUSE/omega/beamnrc/beamnrc.mortran
Labels: bug, small

#1076 Fix #1065: source collection fluence
  HEN_HOUSE/egs++/sources/egs_source_collection/egs_source_collection.cpp
  HEN_HOUSE/egs++/sources/egs_source_collection/egs_source_collection.h
Labels: bug, critical

#1055 Fix #1031: Added pegsless source files to edknrc.make
  HEN_HOUSE/user_codes/edknrc/edknrc.make
Labels: compilation

#1130 Fix #1129: update edk template doc to match manual
  HEN_HOUSE/user_codes/edknrc/edknrc_template.egsinp
Labels: bug, documentation

#1069 Fix egs xyzrepeater bug
  HEN_HOUSE/egs++/geometry/egs_nd_geometry/egs_nd_geometry.h
Labels: bug, critical

#1072 Fix egs_circle_perpendicular critical bug
  HEN_HOUSE/egs++/shapes/egs_circle_perpendicular/egs_circle_perpendicular.h
Labels: bug, critical

#1011 Fix radiative splitting ao
  HEN_HOUSE/egs++/ausgab_objects/egs_fluence_scoring/egs_fluence_scoring.h
  HEN_HOUSE/egs++/ausgab_objects/egs_radiative_splitting/egs_radiative_splitting.cpp
  HEN_HOUSE/egs++/ausgab_objects/egs_radiative_splitting/egs_radiative_splitting.h
  HEN_HOUSE/egs++/egs_advanced_application.cpp
  HEN_HOUSE/egs++/egs_advanced_application.h
  HEN_HOUSE/egs++/egs_application.h
Labels: bug, improvement

#1171 Fix #821: load i_phsp_out when reading dosxyznrc .egsinp file
  HEN_HOUSE/omega/progs/gui/dosxyznrc/load_input2_nrc.tcl
Labels: bug

#1170 Fix #1004: beamdp axis labels are confusing
  HEN_HOUSE/doc/src/pirs3100-g-app/g_template.f
  HEN_HOUSE/egs++/ausgab_objects/egs_fluence_scoring/egs_fluence_scoring.cpp
  HEN_HOUSE/omega/progs/beamdp/beamdp.mortran
  HEN_HOUSE/src/get_media_inputs.mortran
  HEN_HOUSE/user_codes/cavity/cavity.cpp
  HEN_HOUSE/user_codes/edknrc/edknrc.mortran
  HEN_HOUSE/user_codes/egs_kerma/egs_kerma.cpp
  HEN_HOUSE/user_codes/examin/examin.mortran
  HEN_HOUSE/user_codes/sprrznrc/sprrznrc.mortran
Labels: bug

#1100 Add support for Linux aarch64 architecture (ARM)
  HEN_HOUSE/scripts/config.guess
  HEN_HOUSE/scripts/configure
  HEN_HOUSE/scripts/configure_c++
Labels: improvement, installation

#1101 Configuration and documentation for building and running in Codespaces or Development Container
  .devcontainer/README.md
  .devcontainer/build-gui-apps.sh
  .devcontainer/devcontainer.json
  .devcontainer/setup.sh
  .gitignore
Labels: improvement

#1177 Fix (dyn/sync)jaw definition using field dimensions
  HEN_HOUSE/omega/progs/gui/beamnrc/syncjaws.tcl
Labels: bug, gui

#1175 Fix #768: documentation for BEAM_SIZE
  HEN_HOUSE/doc/src/pirs794-dosxyznrc/inputs/dosxyznrc.inp
  HEN_HOUSE/doc/src/pirs794-dosxyznrc/pirs794-dosxyznrc.tex
  HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc.mortran
Labels: documentation
